name: jsd_baselines

channels:
    - defaults
    - conda-forge

dependencies:
    - python=3.6
    - numpy=1.18.4
    - scikit-learn=0.22.1
    - librosa=0.8.0
    - pandas=1.0.3
    - pescador=2.0.0
    - pyyaml=5.1
    # - cudatoolkit=10.0.130=0
    # - cudnn=7.3.1=cuda10.0_0
    - tensorflow=2.0
    - pytest=5.4.2
    - pip
    - pip:
        - mir-eval==0.5
        - tqdm==4.32.2
